from ultralytics import YOLO

MODEL_PATH = "/home/ihpc4090/ZRQ/yolov8_zrq/"
MODEL_WEIGHT = "/home/ihpc4090/ZRQ/yolov8_zrq/runs/detect/"
DATASET_PATH_VEHICLE = "/home/ihpc4090/ZRQ/datasets/VehiclesDetectionDataset/dataset.yaml"
DATASET_PATH_TACO = "/home/ihpc4090/ZRQ/datasets/taco_dataset/data.yaml"
DATASET_PATH_TOMATO = "/home/ihpc4090/ZRQ/datasets/TomatoLeaf/data.yaml"

# model = YOLO(model=MODEL_PATH+"yolov8n_efficientB0backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B0_n",imgsz=224)
# model = YOLO(model=MODEL_PATH+"yolov8n_efficientB1backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B1_n",imgsz=240)
# model = YOLO(model=MODEL_PATH+"yolov8n_efficientB2backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B2_n",imgsz=260)
# model = YOLO(model=MODEL_PATH+"yolov8n_efficientB3backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B3_n",imgsz=300)
# model = YOLO(model=MODEL_PATH+"yolov8n_efficientB4backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B4_n",imgsz=380)

# model = YOLO(model=MODEL_PATH+"yolov8s_efficientB0backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B0_s",imgsz=224)
# model = YOLO(model=MODEL_PATH+"yolov8s_efficientB1backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B1_s",imgsz=240)
# model = YOLO(model=MODEL_PATH+"yolov8s_efficientB2backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B2_s",imgsz=260)
# model = YOLO(model=MODEL_PATH+"yolov8s_efficientB3backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B3_s",imgsz=300)
# model = YOLO(model=MODEL_PATH+"yolov8s_efficientB4backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B4_s",imgsz=380)

# model = YOLO(model=MODEL_PATH+"yolov8m_efficientB0backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B0_m",imgsz=224)
# model = YOLO(model=MODEL_PATH+"yolov8m_efficientB1backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B1_m",imgsz=240)
# model = YOLO(model=MODEL_PATH+"yolov8m_efficientB2backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B2_m",imgsz=260)
# model = YOLO(model=MODEL_PATH+"yolov8m_efficientB3backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B3_m",imgsz=300)
# model = YOLO(model=MODEL_PATH+"yolov8m_efficientB4backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B4_m",imgsz=380)

# model = YOLO(model=MODEL_PATH+"yolov8l_efficientB0backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B0_l",imgsz=224)
# model = YOLO(model=MODEL_PATH+"yolov8l_efficientB1backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B1_l",imgsz=240)
# model = YOLO(model=MODEL_PATH+"yolov8l_efficientB2backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B2_l",imgsz=260)
# model = YOLO(model=MODEL_PATH+"yolov8l_efficientB3backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B3_l",imgsz=300)
# model = YOLO(model=MODEL_PATH+"yolov8l_efficientB4backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B4_l",imgsz=380)

# model = YOLO(model="yolov8n.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Origin_n_224",imgsz=224)
# model = YOLO(model="yolov8n.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Origin_n_240",imgsz=240)
# model = YOLO(model="yolov8n.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Origin_n_260",imgsz=260)
# model = YOLO(model="yolov8n.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Origin_n_300",imgsz=300)
# model = YOLO(model="yolov8n.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Origin_n_380",imgsz=380,pretrained=False)

# model = YOLO(model="yolov8s.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Origin_s_224",imgsz=224)
# model = YOLO(model="yolov8s.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Origin_s_240",imgsz=240)
# model = YOLO(model="yolov8s.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Origin_s_260",imgsz=260)
# model = YOLO(model="yolov8s.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Origin_s_300",imgsz=300)
# model = YOLO(model="yolov8s.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Origin_s_380",imgsz=380)

# model = YOLO(model="yolov8m.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Origin_m_224",imgsz=224)
# model = YOLO(model="yolov8m.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Origin_m_240",imgsz=240)
# model = YOLO(model="yolov8m.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Origin_m_260",imgsz=260)
# model = YOLO(model="yolov8m.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Origin_m_300",imgsz=300)
# model = YOLO(model="yolov8m.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Origin_m_380",imgsz=380)

# model = YOLO(model="yolov8l.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Origin_l_224",imgsz=224)
# model = YOLO(model="yolov8l.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Origin_l_240",imgsz=240)
# model = YOLO(model="yolov8l.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Origin_l_260",imgsz=260)
# model = YOLO(model="yolov8l.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Origin_l_300",imgsz=300)
# model = YOLO(model="yolov8l.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Origin_l_380",imgsz=380)


# model = YOLO(model=MODEL_PATH+"yolov8n_efficientB3backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B3_n",imgsz=300)
# model = YOLO(model=MODEL_PATH+"yolov8s_efficientB3backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B3_s",imgsz=300)
# model = YOLO(model=MODEL_PATH+"yolov8m_efficientB3backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B3_m",imgsz=300)
# model = YOLO(model=MODEL_PATH+"yolov8l_efficientB3backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B3_l",imgsz=300)



model = YOLO(model=MODEL_PATH+"yolov8n_efficientB0backbone.yaml")
model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B0_n_nosz_test")
# model = YOLO(model=MODEL_PATH+"yolov8n_efficientB1backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B1_n_nosz")
# model = YOLO(model=MODEL_PATH+"yolov8n_efficientB2backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B2_n_nosz")
# model = YOLO(model=MODEL_PATH+"yolov8n_efficientB3backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B3_n_nosz")
# model = YOLO(model=MODEL_PATH+"yolov8n_efficientB4backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B4_n_nosz")

# model = YOLO(model=MODEL_PATH+"yolov8s_efficientB0backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B0_s_nosz")
# model = YOLO(model=MODEL_PATH+"yolov8s_efficientB1backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B1_s_nosz")
# model = YOLO(model=MODEL_PATH+"yolov8s_efficientB2backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B2_s_nosz")
# model = YOLO(model=MODEL_PATH+"yolov8s_efficientB3backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B3_s_nosz")
# model = YOLO(model=MODEL_PATH+"yolov8s_efficientB4backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B4_s_nosz")

# model = YOLO(model=MODEL_PATH+"yolov8m_efficientB0backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B0_m_nosz")
# model = YOLO(model=MODEL_PATH+"yolov8m_efficientB1backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B1_m_nosz")
# model = YOLO(model=MODEL_PATH+"yolov8m_efficientB2backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B2_m_nosz")
# model = YOLO(model=MODEL_PATH+"yolov8m_efficientB3backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B3_m_nosz")
# model = YOLO(model=MODEL_PATH+"yolov8m_efficientB4backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B4_m_nosz")

# model = YOLO(model=MODEL_PATH+"yolov8l_efficientB0backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B0_l_nosz")
# model = YOLO(model=MODEL_PATH+"yolov8l_efficientB1backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B1_l_nosz")
# model = YOLO(model=MODEL_PATH+"yolov8l_efficientB2backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B2_l_nosz")
# model = YOLO(model=MODEL_PATH+"yolov8l_efficientB3backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B3_l_nosz")
# model = YOLO(model=MODEL_PATH+"yolov8l_efficientB4backbone.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Effi_B4_l_nosz")


# model = YOLO(model="yolov8n.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Origin_n_nosz")
# model = YOLO(model="yolov8s.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Origin_s_nosz")
# model = YOLO(model="yolov8m.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Origin_m_nosz")
# model = YOLO(model="yolov8l.yaml")
# model.train(epochs=500,data=DATASET_PATH_TOMATO,name="Origin_l_nosz")